import CoreGraphics
import CoreText
import Foundation
import ImageIO
import UniformTypeIdentifiers

/// Sample data for a simulator (Device ▸ Add Sample Data): fake contacts and
/// numbered placeholder pictures, generated the same way every time and added
/// with `simctl addmedia`. Everything is clearly fake: contacts are named
/// "Sample Contact 01" with `example.com` addresses and 555-01xx numbers
/// (the range reserved for fiction); pictures say "Sample Photo n".
///
/// Calendar, Reminders and Health have no simctl route and no public
/// framework on the Mac that writes into a simulator's stores; they would
/// need a helper app installed on the simulator (EventKit, HealthKit).
public enum SimulatorSampleData {
    public static let maximumContacts = 500
    public static let maximumPhotos = 100

    public enum SampleDataError: Error, Equatable, CustomStringConvertible {
        case invalidCount(Int, maximum: Int)
        case renderFailed(Int)

        public var description: String {
            switch self {
            case .invalidCount(let count, let maximum): "\(count) is not between 1 and \(maximum)."
            case .renderFailed(let number): "Could not draw sample photo \(number)."
            }
        }
    }

    /// The name of contact `number` (1-based), zero-padded to the width of `count`.
    public static func contactName(_ number: Int, of count: Int) -> String {
        let width = max(2, String(count).count)
        return "Sample Contact " + String(format: "%0\(width)d", number)
    }

    /// A vCard 3.0 file holding `count` fake contacts.
    public static func contactsVCard(count: Int) throws -> String {
        guard (1...maximumContacts).contains(count) else {
            throw SampleDataError.invalidCount(count, maximum: maximumContacts)
        }
        var lines: [String] = []
        for number in 1...count {
            let padded = String(format: "%0\(max(2, String(count).count))d", number)
            lines += [
                "BEGIN:VCARD",
                "VERSION:3.0",
                "N:Contact \(padded);Sample;;;",
                "FN:\(contactName(number, of: count))",
                "ORG:Device Hub Pro Sample Data",
                "TEL;TYPE=CELL:+1 555 01\(String(format: "%02d", number % 100))",
                "EMAIL;TYPE=INTERNET:sample.contact\(padded)@example.com",
                "NOTE:Fake contact generated by Device Hub Pro.",
                "END:VCARD",
            ]
        }
        return lines.joined(separator: "\r\n") + "\r\n"
    }

    /// Writes the contacts file into `folder` and returns it.
    public static func writeContacts(count: Int, to folder: URL) throws -> URL {
        let card = try contactsVCard(count: count)
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let file = folder.appendingPathComponent("Sample Contacts \(count).vcf")
        try Data(card.utf8).write(to: file)
        return file
    }

    /// The background colour (red, green, blue in 0…1) of photo `number`: hues
    /// spread by the golden ratio so neighbours differ.
    public static func photoColor(_ number: Int) -> (red: Double, green: Double, blue: Double) {
        let hue = (Double(number) * 0.618_033_988_75).truncatingRemainder(dividingBy: 1)
        // HSV with saturation 0.55 and value 0.85, converted by hand.
        let saturation = 0.55
        let value = 0.85
        let sector = Int(hue * 6) % 6
        let fraction = hue * 6 - Double(Int(hue * 6))
        let p = value * (1 - saturation)
        let q = value * (1 - fraction * saturation)
        let t = value * (1 - (1 - fraction) * saturation)
        switch sector {
        case 0: return (value, t, p)
        case 1: return (q, value, p)
        case 2: return (p, value, t)
        case 3: return (p, q, value)
        case 4: return (t, p, value)
        default: return (value, p, q)
        }
    }

    /// PNG bytes of placeholder photo `number` of `count`: a flat colour with
    /// the number large in the middle and "Sample Photo n of count" under it.
    public static func photoPNG(number: Int, of count: Int, width: Int = 1200, height: Int = 900) throws -> Data {
        let space = CGColorSpaceCreateDeviceRGB()
        guard let context = CGContext(
            data: nil, width: width, height: height, bitsPerComponent: 8, bytesPerRow: 0,
            space: space, bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ) else { throw SampleDataError.renderFailed(number) }
        let color = photoColor(number)
        context.setFillColor(red: color.red, green: color.green, blue: color.blue, alpha: 1)
        context.fill(CGRect(x: 0, y: 0, width: width, height: height))
        draw("\(number)", size: CGFloat(height) * 0.5, centerY: CGFloat(height) * 0.55, width: width, in: context)
        draw("Sample Photo \(number) of \(count)", size: CGFloat(height) * 0.06, centerY: CGFloat(height) * 0.18, width: width, in: context)
        guard let image = context.makeImage() else { throw SampleDataError.renderFailed(number) }
        let data = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(data, UTType.png.identifier as CFString, 1, nil) else {
            throw SampleDataError.renderFailed(number)
        }
        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination) else { throw SampleDataError.renderFailed(number) }
        return data as Data
    }

    private static func draw(_ text: String, size: CGFloat, centerY: CGFloat, width: Int, in context: CGContext) {
        let font = CTFontCreateWithName("Helvetica-Bold" as CFString, size, nil)
        let attributes: [CFString: Any] = [
            kCTFontAttributeName: font,
            kCTForegroundColorFromContextAttributeName: true,
        ]
        let string = CFAttributedStringCreate(nil, text as CFString, attributes as CFDictionary)!
        let line = CTLineCreateWithAttributedString(string)
        let bounds = CTLineGetBoundsWithOptions(line, [])
        context.setFillColor(red: 1, green: 1, blue: 1, alpha: 1)
        context.textPosition = CGPoint(x: (CGFloat(width) - bounds.width) / 2 - bounds.minX, y: centerY - bounds.height / 2)
        CTLineDraw(line, context)
    }

    /// Writes `count` numbered PNGs (`Sample Photo 01.png` …) into `folder`.
    public static func writePhotos(count: Int, to folder: URL) throws -> [URL] {
        guard (1...maximumPhotos).contains(count) else {
            throw SampleDataError.invalidCount(count, maximum: maximumPhotos)
        }
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let width = max(2, String(count).count)
        return try (1...count).map { number in
            let file = folder.appendingPathComponent("Sample Photo " + String(format: "%0\(width)d", number) + ".png")
            try photoPNG(number: number, of: count).write(to: file)
            return file
        }
    }
}
